// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { CAPosition, CAPositionData, CAPositionTableId } from "./tables/CAPosition.sol";
import { CAVoxelType, CAVoxelTypeData, CAVoxelTypeTableId } from "./tables/CAVoxelType.sol";
import { ElectronTunnelSpot, ElectronTunnelSpotTableId } from "./tables/ElectronTunnelSpot.sol";
