// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

// Import schema type
import { SchemaType } from "@latticexyz/schema-type/src/solidity/SchemaType.sol";

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { Schema, SchemaLib } from "@latticexyz/store/src/Schema.sol";
import { PackedCounter, PackedCounterLib } from "@latticexyz/store/src/PackedCounter.sol";

bytes32 constant _tableId = bytes32(abi.encodePacked(bytes16(""), bytes16("CAEntityReverseM")));
bytes32 constant CAEntityReverseMappingTableId = _tableId;

struct CAEntityReverseMappingData {
  address callerAddress;
  bytes32 entity;
}

library CAEntityReverseMapping {
  /** Get the table's schema */
  function getSchema() internal pure returns (Schema) {
    SchemaType[] memory _schema = new SchemaType[](2);
    _schema[0] = SchemaType.ADDRESS;
    _schema[1] = SchemaType.BYTES32;

    return SchemaLib.encode(_schema);
  }

  function getKeySchema() internal pure returns (Schema) {
    SchemaType[] memory _schema = new SchemaType[](1);
    _schema[0] = SchemaType.BYTES32;

    return SchemaLib.encode(_schema);
  }

  /** Get the table's metadata */
  function getMetadata() internal pure returns (string memory, string[] memory) {
    string[] memory _fieldNames = new string[](2);
    _fieldNames[0] = "callerAddress";
    _fieldNames[1] = "entity";
    return ("CAEntityReverseMapping", _fieldNames);
  }

  /** Register the table's schema */
  function registerSchema() internal {
    StoreSwitch.registerSchema(_tableId, getSchema(), getKeySchema());
  }

  /** Register the table's schema (using the specified store) */
  function registerSchema(IStore _store) internal {
    _store.registerSchema(_tableId, getSchema(), getKeySchema());
  }

  /** Set the table's metadata */
  function setMetadata() internal {
    (string memory _tableName, string[] memory _fieldNames) = getMetadata();
    StoreSwitch.setMetadata(_tableId, _tableName, _fieldNames);
  }

  /** Set the table's metadata (using the specified store) */
  function setMetadata(IStore _store) internal {
    (string memory _tableName, string[] memory _fieldNames) = getMetadata();
    _store.setMetadata(_tableId, _tableName, _fieldNames);
  }

  /** Get callerAddress */
  function getCallerAddress(bytes32 caEntity) internal view returns (address callerAddress) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = caEntity;

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 0);
    return (address(Bytes.slice20(_blob, 0)));
  }

  /** Get callerAddress (using the specified store) */
  function getCallerAddress(IStore _store, bytes32 caEntity) internal view returns (address callerAddress) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = caEntity;

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 0);
    return (address(Bytes.slice20(_blob, 0)));
  }

  /** Set callerAddress */
  function setCallerAddress(bytes32 caEntity, address callerAddress) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = caEntity;

    StoreSwitch.setField(_tableId, _keyTuple, 0, abi.encodePacked((callerAddress)));
  }

  /** Set callerAddress (using the specified store) */
  function setCallerAddress(IStore _store, bytes32 caEntity, address callerAddress) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = caEntity;

    _store.setField(_tableId, _keyTuple, 0, abi.encodePacked((callerAddress)));
  }

  /** Get entity */
  function getEntity(bytes32 caEntity) internal view returns (bytes32 entity) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = caEntity;

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 1);
    return (Bytes.slice32(_blob, 0));
  }

  /** Get entity (using the specified store) */
  function getEntity(IStore _store, bytes32 caEntity) internal view returns (bytes32 entity) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = caEntity;

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 1);
    return (Bytes.slice32(_blob, 0));
  }

  /** Set entity */
  function setEntity(bytes32 caEntity, bytes32 entity) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = caEntity;

    StoreSwitch.setField(_tableId, _keyTuple, 1, abi.encodePacked((entity)));
  }

  /** Set entity (using the specified store) */
  function setEntity(IStore _store, bytes32 caEntity, bytes32 entity) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = caEntity;

    _store.setField(_tableId, _keyTuple, 1, abi.encodePacked((entity)));
  }

  /** Get the full data */
  function get(bytes32 caEntity) internal view returns (CAEntityReverseMappingData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = caEntity;

    bytes memory _blob = StoreSwitch.getRecord(_tableId, _keyTuple, getSchema());
    return decode(_blob);
  }

  /** Get the full data (using the specified store) */
  function get(IStore _store, bytes32 caEntity) internal view returns (CAEntityReverseMappingData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = caEntity;

    bytes memory _blob = _store.getRecord(_tableId, _keyTuple, getSchema());
    return decode(_blob);
  }

  /** Set the full data using individual values */
  function set(bytes32 caEntity, address callerAddress, bytes32 entity) internal {
    bytes memory _data = encode(callerAddress, entity);

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = caEntity;

    StoreSwitch.setRecord(_tableId, _keyTuple, _data);
  }

  /** Set the full data using individual values (using the specified store) */
  function set(IStore _store, bytes32 caEntity, address callerAddress, bytes32 entity) internal {
    bytes memory _data = encode(callerAddress, entity);

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = caEntity;

    _store.setRecord(_tableId, _keyTuple, _data);
  }

  /** Set the full data using the data struct */
  function set(bytes32 caEntity, CAEntityReverseMappingData memory _table) internal {
    set(caEntity, _table.callerAddress, _table.entity);
  }

  /** Set the full data using the data struct (using the specified store) */
  function set(IStore _store, bytes32 caEntity, CAEntityReverseMappingData memory _table) internal {
    set(_store, caEntity, _table.callerAddress, _table.entity);
  }

  /** Decode the tightly packed blob using this table's schema */
  function decode(bytes memory _blob) internal pure returns (CAEntityReverseMappingData memory _table) {
    _table.callerAddress = (address(Bytes.slice20(_blob, 0)));

    _table.entity = (Bytes.slice32(_blob, 20));
  }

  /** Tightly pack full data using this table's schema */
  function encode(address callerAddress, bytes32 entity) internal pure returns (bytes memory) {
    return abi.encodePacked(callerAddress, entity);
  }

  /** Encode keys as a bytes32 array using this table's schema */
  function encodeKeyTuple(bytes32 caEntity) internal pure returns (bytes32[] memory _keyTuple) {
    _keyTuple = new bytes32[](1);
    _keyTuple[0] = caEntity;
  }

  /* Delete all data for given keys */
  function deleteRecord(bytes32 caEntity) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = caEntity;

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /* Delete all data for given keys (using the specified store) */
  function deleteRecord(IStore _store, bytes32 caEntity) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = caEntity;

    _store.deleteRecord(_tableId, _keyTuple);
  }
}
