// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

// Import schema type
import { SchemaType } from "@latticexyz/schema-type/src/solidity/SchemaType.sol";

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { Schema, SchemaLib } from "@latticexyz/store/src/Schema.sol";
import { PackedCounter, PackedCounterLib } from "@latticexyz/store/src/PackedCounter.sol";

bytes32 constant _tableId = bytes32(abi.encodePacked(bytes16(""), bytes16("VoxelType")));
bytes32 constant VoxelTypeTableId = _tableId;

struct VoxelTypeData {
  bytes32 voxelTypeId;
  bytes32 voxelVariantId;
}

library VoxelType {
  /** Get the table's schema */
  function getSchema() internal pure returns (Schema) {
    SchemaType[] memory _schema = new SchemaType[](2);
    _schema[0] = SchemaType.BYTES32;
    _schema[1] = SchemaType.BYTES32;

    return SchemaLib.encode(_schema);
  }

  function getKeySchema() internal pure returns (Schema) {
    SchemaType[] memory _schema = new SchemaType[](2);
    _schema[0] = SchemaType.ADDRESS;
    _schema[1] = SchemaType.BYTES32;

    return SchemaLib.encode(_schema);
  }

  /** Get the table's metadata */
  function getMetadata() internal pure returns (string memory, string[] memory) {
    string[] memory _fieldNames = new string[](2);
    _fieldNames[0] = "voxelTypeId";
    _fieldNames[1] = "voxelVariantId";
    return ("VoxelType", _fieldNames);
  }

  /** Register the table's schema */
  function registerSchema() internal {
    StoreSwitch.registerSchema(_tableId, getSchema(), getKeySchema());
  }

  /** Register the table's schema (using the specified store) */
  function registerSchema(IStore _store) internal {
    _store.registerSchema(_tableId, getSchema(), getKeySchema());
  }

  /** Set the table's metadata */
  function setMetadata() internal {
    (string memory _tableName, string[] memory _fieldNames) = getMetadata();
    StoreSwitch.setMetadata(_tableId, _tableName, _fieldNames);
  }

  /** Set the table's metadata (using the specified store) */
  function setMetadata(IStore _store) internal {
    (string memory _tableName, string[] memory _fieldNames) = getMetadata();
    _store.setMetadata(_tableId, _tableName, _fieldNames);
  }

  /** Get voxelTypeId */
  function getVoxelTypeId(address callerAddress, bytes32 entity) internal view returns (bytes32 voxelTypeId) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(callerAddress)));
    _keyTuple[1] = entity;

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 0);
    return (Bytes.slice32(_blob, 0));
  }

  /** Get voxelTypeId (using the specified store) */
  function getVoxelTypeId(
    IStore _store,
    address callerAddress,
    bytes32 entity
  ) internal view returns (bytes32 voxelTypeId) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(callerAddress)));
    _keyTuple[1] = entity;

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 0);
    return (Bytes.slice32(_blob, 0));
  }

  /** Set voxelTypeId */
  function setVoxelTypeId(address callerAddress, bytes32 entity, bytes32 voxelTypeId) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(callerAddress)));
    _keyTuple[1] = entity;

    StoreSwitch.setField(_tableId, _keyTuple, 0, abi.encodePacked((voxelTypeId)));
  }

  /** Set voxelTypeId (using the specified store) */
  function setVoxelTypeId(IStore _store, address callerAddress, bytes32 entity, bytes32 voxelTypeId) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(callerAddress)));
    _keyTuple[1] = entity;

    _store.setField(_tableId, _keyTuple, 0, abi.encodePacked((voxelTypeId)));
  }

  /** Get voxelVariantId */
  function getVoxelVariantId(address callerAddress, bytes32 entity) internal view returns (bytes32 voxelVariantId) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(callerAddress)));
    _keyTuple[1] = entity;

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 1);
    return (Bytes.slice32(_blob, 0));
  }

  /** Get voxelVariantId (using the specified store) */
  function getVoxelVariantId(
    IStore _store,
    address callerAddress,
    bytes32 entity
  ) internal view returns (bytes32 voxelVariantId) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(callerAddress)));
    _keyTuple[1] = entity;

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 1);
    return (Bytes.slice32(_blob, 0));
  }

  /** Set voxelVariantId */
  function setVoxelVariantId(address callerAddress, bytes32 entity, bytes32 voxelVariantId) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(callerAddress)));
    _keyTuple[1] = entity;

    StoreSwitch.setField(_tableId, _keyTuple, 1, abi.encodePacked((voxelVariantId)));
  }

  /** Set voxelVariantId (using the specified store) */
  function setVoxelVariantId(IStore _store, address callerAddress, bytes32 entity, bytes32 voxelVariantId) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(callerAddress)));
    _keyTuple[1] = entity;

    _store.setField(_tableId, _keyTuple, 1, abi.encodePacked((voxelVariantId)));
  }

  /** Get the full data */
  function get(address callerAddress, bytes32 entity) internal view returns (VoxelTypeData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(callerAddress)));
    _keyTuple[1] = entity;

    bytes memory _blob = StoreSwitch.getRecord(_tableId, _keyTuple, getSchema());
    return decode(_blob);
  }

  /** Get the full data (using the specified store) */
  function get(
    IStore _store,
    address callerAddress,
    bytes32 entity
  ) internal view returns (VoxelTypeData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(callerAddress)));
    _keyTuple[1] = entity;

    bytes memory _blob = _store.getRecord(_tableId, _keyTuple, getSchema());
    return decode(_blob);
  }

  /** Set the full data using individual values */
  function set(address callerAddress, bytes32 entity, bytes32 voxelTypeId, bytes32 voxelVariantId) internal {
    bytes memory _data = encode(voxelTypeId, voxelVariantId);

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(callerAddress)));
    _keyTuple[1] = entity;

    StoreSwitch.setRecord(_tableId, _keyTuple, _data);
  }

  /** Set the full data using individual values (using the specified store) */
  function set(
    IStore _store,
    address callerAddress,
    bytes32 entity,
    bytes32 voxelTypeId,
    bytes32 voxelVariantId
  ) internal {
    bytes memory _data = encode(voxelTypeId, voxelVariantId);

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(callerAddress)));
    _keyTuple[1] = entity;

    _store.setRecord(_tableId, _keyTuple, _data);
  }

  /** Set the full data using the data struct */
  function set(address callerAddress, bytes32 entity, VoxelTypeData memory _table) internal {
    set(callerAddress, entity, _table.voxelTypeId, _table.voxelVariantId);
  }

  /** Set the full data using the data struct (using the specified store) */
  function set(IStore _store, address callerAddress, bytes32 entity, VoxelTypeData memory _table) internal {
    set(_store, callerAddress, entity, _table.voxelTypeId, _table.voxelVariantId);
  }

  /** Decode the tightly packed blob using this table's schema */
  function decode(bytes memory _blob) internal pure returns (VoxelTypeData memory _table) {
    _table.voxelTypeId = (Bytes.slice32(_blob, 0));

    _table.voxelVariantId = (Bytes.slice32(_blob, 32));
  }

  /** Tightly pack full data using this table's schema */
  function encode(bytes32 voxelTypeId, bytes32 voxelVariantId) internal view returns (bytes memory) {
    return abi.encodePacked(voxelTypeId, voxelVariantId);
  }

  /** Encode keys as a bytes32 array using this table's schema */
  function encodeKeyTuple(address callerAddress, bytes32 entity) internal pure returns (bytes32[] memory _keyTuple) {
    _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(callerAddress)));
    _keyTuple[1] = entity;
  }

  /* Delete all data for given keys */
  function deleteRecord(address callerAddress, bytes32 entity) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(callerAddress)));
    _keyTuple[1] = entity;

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /* Delete all data for given keys (using the specified store) */
  function deleteRecord(IStore _store, address callerAddress, bytes32 entity) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(callerAddress)));
    _keyTuple[1] = entity;

    _store.deleteRecord(_tableId, _keyTuple);
  }
}
