// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IWorldObjectEventSystem {
  function preRunObjectInteraction(bytes32 centerObjectEntityId, bytes32[] memory neighbourObjectEntityIds) external;
}
