// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

// Import schema type
import { SchemaType } from "@latticexyz/schema-type/src/solidity/SchemaType.sol";

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { Schema, SchemaLib } from "@latticexyz/store/src/Schema.sol";
import { PackedCounter, PackedCounterLib } from "@latticexyz/store/src/PackedCounter.sol";

bytes32 constant _tableId = bytes32(abi.encodePacked(bytes16(""), bytes16("CreationRegistry")));
bytes32 constant CreationRegistryTableId = _tableId;

struct CreationRegistryData {
  uint32 numVoxels;
  bytes voxelTypes;
  bytes relativePositions;
  bytes baseCreations;
  bytes metadata;
}

library CreationRegistry {
  /** Get the table's key schema */
  function getKeySchema() internal pure returns (Schema) {
    SchemaType[] memory _schema = new SchemaType[](1);
    _schema[0] = SchemaType.BYTES32;

    return SchemaLib.encode(_schema);
  }

  /** Get the table's value schema */
  function getValueSchema() internal pure returns (Schema) {
    SchemaType[] memory _schema = new SchemaType[](5);
    _schema[0] = SchemaType.UINT32;
    _schema[1] = SchemaType.BYTES;
    _schema[2] = SchemaType.BYTES;
    _schema[3] = SchemaType.BYTES;
    _schema[4] = SchemaType.BYTES;

    return SchemaLib.encode(_schema);
  }

  /** Get the table's key names */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](1);
    keyNames[0] = "creationId";
  }

  /** Get the table's field names */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](5);
    fieldNames[0] = "numVoxels";
    fieldNames[1] = "voxelTypes";
    fieldNames[2] = "relativePositions";
    fieldNames[3] = "baseCreations";
    fieldNames[4] = "metadata";
  }

  /** Register the table's key schema, value schema, key names and value names */
  function register() internal {
    StoreSwitch.registerTable(_tableId, getKeySchema(), getValueSchema(), getKeyNames(), getFieldNames());
  }

  /** Register the table's key schema, value schema, key names and value names (using the specified store) */
  function register(IStore _store) internal {
    _store.registerTable(_tableId, getKeySchema(), getValueSchema(), getKeyNames(), getFieldNames());
  }

  /** Get numVoxels */
  function getNumVoxels(bytes32 creationId) internal view returns (uint32 numVoxels) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = creationId;

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 0, getValueSchema());
    return (uint32(Bytes.slice4(_blob, 0)));
  }

  /** Get numVoxels (using the specified store) */
  function getNumVoxels(IStore _store, bytes32 creationId) internal view returns (uint32 numVoxels) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = creationId;

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 0, getValueSchema());
    return (uint32(Bytes.slice4(_blob, 0)));
  }

  /** Set numVoxels */
  function setNumVoxels(bytes32 creationId, uint32 numVoxels) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = creationId;

    StoreSwitch.setField(_tableId, _keyTuple, 0, abi.encodePacked((numVoxels)), getValueSchema());
  }

  /** Set numVoxels (using the specified store) */
  function setNumVoxels(IStore _store, bytes32 creationId, uint32 numVoxels) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = creationId;

    _store.setField(_tableId, _keyTuple, 0, abi.encodePacked((numVoxels)), getValueSchema());
  }

  /** Get voxelTypes */
  function getVoxelTypes(bytes32 creationId) internal view returns (bytes memory voxelTypes) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = creationId;

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 1, getValueSchema());
    return (bytes(_blob));
  }

  /** Get voxelTypes (using the specified store) */
  function getVoxelTypes(IStore _store, bytes32 creationId) internal view returns (bytes memory voxelTypes) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = creationId;

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 1, getValueSchema());
    return (bytes(_blob));
  }

  /** Set voxelTypes */
  function setVoxelTypes(bytes32 creationId, bytes memory voxelTypes) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = creationId;

    StoreSwitch.setField(_tableId, _keyTuple, 1, bytes((voxelTypes)), getValueSchema());
  }

  /** Set voxelTypes (using the specified store) */
  function setVoxelTypes(IStore _store, bytes32 creationId, bytes memory voxelTypes) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = creationId;

    _store.setField(_tableId, _keyTuple, 1, bytes((voxelTypes)), getValueSchema());
  }

  /** Get the length of voxelTypes */
  function lengthVoxelTypes(bytes32 creationId) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = creationId;

    uint256 _byteLength = StoreSwitch.getFieldLength(_tableId, _keyTuple, 1, getValueSchema());
    unchecked {
      return _byteLength / 1;
    }
  }

  /** Get the length of voxelTypes (using the specified store) */
  function lengthVoxelTypes(IStore _store, bytes32 creationId) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = creationId;

    uint256 _byteLength = _store.getFieldLength(_tableId, _keyTuple, 1, getValueSchema());
    unchecked {
      return _byteLength / 1;
    }
  }

  /**
   * Get an item of voxelTypes
   * (unchecked, returns invalid data if index overflows)
   */
  function getItemVoxelTypes(bytes32 creationId, uint256 _index) internal view returns (bytes memory) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = creationId;

    unchecked {
      bytes memory _blob = StoreSwitch.getFieldSlice(
        _tableId,
        _keyTuple,
        1,
        getValueSchema(),
        _index * 1,
        (_index + 1) * 1
      );
      return (bytes(_blob));
    }
  }

  /**
   * Get an item of voxelTypes (using the specified store)
   * (unchecked, returns invalid data if index overflows)
   */
  function getItemVoxelTypes(IStore _store, bytes32 creationId, uint256 _index) internal view returns (bytes memory) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = creationId;

    unchecked {
      bytes memory _blob = _store.getFieldSlice(_tableId, _keyTuple, 1, getValueSchema(), _index * 1, (_index + 1) * 1);
      return (bytes(_blob));
    }
  }

  /** Push a slice to voxelTypes */
  function pushVoxelTypes(bytes32 creationId, bytes memory _slice) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = creationId;

    StoreSwitch.pushToField(_tableId, _keyTuple, 1, bytes((_slice)), getValueSchema());
  }

  /** Push a slice to voxelTypes (using the specified store) */
  function pushVoxelTypes(IStore _store, bytes32 creationId, bytes memory _slice) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = creationId;

    _store.pushToField(_tableId, _keyTuple, 1, bytes((_slice)), getValueSchema());
  }

  /** Pop a slice from voxelTypes */
  function popVoxelTypes(bytes32 creationId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = creationId;

    StoreSwitch.popFromField(_tableId, _keyTuple, 1, 1, getValueSchema());
  }

  /** Pop a slice from voxelTypes (using the specified store) */
  function popVoxelTypes(IStore _store, bytes32 creationId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = creationId;

    _store.popFromField(_tableId, _keyTuple, 1, 1, getValueSchema());
  }

  /**
   * Update a slice of voxelTypes at `_index`
   * (checked only to prevent modifying other tables; can corrupt own data if index overflows)
   */
  function updateVoxelTypes(bytes32 creationId, uint256 _index, bytes memory _slice) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = creationId;

    unchecked {
      StoreSwitch.updateInField(_tableId, _keyTuple, 1, _index * 1, bytes((_slice)), getValueSchema());
    }
  }

  /**
   * Update a slice of voxelTypes (using the specified store) at `_index`
   * (checked only to prevent modifying other tables; can corrupt own data if index overflows)
   */
  function updateVoxelTypes(IStore _store, bytes32 creationId, uint256 _index, bytes memory _slice) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = creationId;

    unchecked {
      _store.updateInField(_tableId, _keyTuple, 1, _index * 1, bytes((_slice)), getValueSchema());
    }
  }

  /** Get relativePositions */
  function getRelativePositions(bytes32 creationId) internal view returns (bytes memory relativePositions) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = creationId;

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 2, getValueSchema());
    return (bytes(_blob));
  }

  /** Get relativePositions (using the specified store) */
  function getRelativePositions(
    IStore _store,
    bytes32 creationId
  ) internal view returns (bytes memory relativePositions) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = creationId;

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 2, getValueSchema());
    return (bytes(_blob));
  }

  /** Set relativePositions */
  function setRelativePositions(bytes32 creationId, bytes memory relativePositions) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = creationId;

    StoreSwitch.setField(_tableId, _keyTuple, 2, bytes((relativePositions)), getValueSchema());
  }

  /** Set relativePositions (using the specified store) */
  function setRelativePositions(IStore _store, bytes32 creationId, bytes memory relativePositions) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = creationId;

    _store.setField(_tableId, _keyTuple, 2, bytes((relativePositions)), getValueSchema());
  }

  /** Get the length of relativePositions */
  function lengthRelativePositions(bytes32 creationId) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = creationId;

    uint256 _byteLength = StoreSwitch.getFieldLength(_tableId, _keyTuple, 2, getValueSchema());
    unchecked {
      return _byteLength / 1;
    }
  }

  /** Get the length of relativePositions (using the specified store) */
  function lengthRelativePositions(IStore _store, bytes32 creationId) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = creationId;

    uint256 _byteLength = _store.getFieldLength(_tableId, _keyTuple, 2, getValueSchema());
    unchecked {
      return _byteLength / 1;
    }
  }

  /**
   * Get an item of relativePositions
   * (unchecked, returns invalid data if index overflows)
   */
  function getItemRelativePositions(bytes32 creationId, uint256 _index) internal view returns (bytes memory) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = creationId;

    unchecked {
      bytes memory _blob = StoreSwitch.getFieldSlice(
        _tableId,
        _keyTuple,
        2,
        getValueSchema(),
        _index * 1,
        (_index + 1) * 1
      );
      return (bytes(_blob));
    }
  }

  /**
   * Get an item of relativePositions (using the specified store)
   * (unchecked, returns invalid data if index overflows)
   */
  function getItemRelativePositions(
    IStore _store,
    bytes32 creationId,
    uint256 _index
  ) internal view returns (bytes memory) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = creationId;

    unchecked {
      bytes memory _blob = _store.getFieldSlice(_tableId, _keyTuple, 2, getValueSchema(), _index * 1, (_index + 1) * 1);
      return (bytes(_blob));
    }
  }

  /** Push a slice to relativePositions */
  function pushRelativePositions(bytes32 creationId, bytes memory _slice) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = creationId;

    StoreSwitch.pushToField(_tableId, _keyTuple, 2, bytes((_slice)), getValueSchema());
  }

  /** Push a slice to relativePositions (using the specified store) */
  function pushRelativePositions(IStore _store, bytes32 creationId, bytes memory _slice) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = creationId;

    _store.pushToField(_tableId, _keyTuple, 2, bytes((_slice)), getValueSchema());
  }

  /** Pop a slice from relativePositions */
  function popRelativePositions(bytes32 creationId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = creationId;

    StoreSwitch.popFromField(_tableId, _keyTuple, 2, 1, getValueSchema());
  }

  /** Pop a slice from relativePositions (using the specified store) */
  function popRelativePositions(IStore _store, bytes32 creationId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = creationId;

    _store.popFromField(_tableId, _keyTuple, 2, 1, getValueSchema());
  }

  /**
   * Update a slice of relativePositions at `_index`
   * (checked only to prevent modifying other tables; can corrupt own data if index overflows)
   */
  function updateRelativePositions(bytes32 creationId, uint256 _index, bytes memory _slice) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = creationId;

    unchecked {
      StoreSwitch.updateInField(_tableId, _keyTuple, 2, _index * 1, bytes((_slice)), getValueSchema());
    }
  }

  /**
   * Update a slice of relativePositions (using the specified store) at `_index`
   * (checked only to prevent modifying other tables; can corrupt own data if index overflows)
   */
  function updateRelativePositions(IStore _store, bytes32 creationId, uint256 _index, bytes memory _slice) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = creationId;

    unchecked {
      _store.updateInField(_tableId, _keyTuple, 2, _index * 1, bytes((_slice)), getValueSchema());
    }
  }

  /** Get baseCreations */
  function getBaseCreations(bytes32 creationId) internal view returns (bytes memory baseCreations) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = creationId;

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 3, getValueSchema());
    return (bytes(_blob));
  }

  /** Get baseCreations (using the specified store) */
  function getBaseCreations(IStore _store, bytes32 creationId) internal view returns (bytes memory baseCreations) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = creationId;

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 3, getValueSchema());
    return (bytes(_blob));
  }

  /** Set baseCreations */
  function setBaseCreations(bytes32 creationId, bytes memory baseCreations) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = creationId;

    StoreSwitch.setField(_tableId, _keyTuple, 3, bytes((baseCreations)), getValueSchema());
  }

  /** Set baseCreations (using the specified store) */
  function setBaseCreations(IStore _store, bytes32 creationId, bytes memory baseCreations) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = creationId;

    _store.setField(_tableId, _keyTuple, 3, bytes((baseCreations)), getValueSchema());
  }

  /** Get the length of baseCreations */
  function lengthBaseCreations(bytes32 creationId) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = creationId;

    uint256 _byteLength = StoreSwitch.getFieldLength(_tableId, _keyTuple, 3, getValueSchema());
    unchecked {
      return _byteLength / 1;
    }
  }

  /** Get the length of baseCreations (using the specified store) */
  function lengthBaseCreations(IStore _store, bytes32 creationId) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = creationId;

    uint256 _byteLength = _store.getFieldLength(_tableId, _keyTuple, 3, getValueSchema());
    unchecked {
      return _byteLength / 1;
    }
  }

  /**
   * Get an item of baseCreations
   * (unchecked, returns invalid data if index overflows)
   */
  function getItemBaseCreations(bytes32 creationId, uint256 _index) internal view returns (bytes memory) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = creationId;

    unchecked {
      bytes memory _blob = StoreSwitch.getFieldSlice(
        _tableId,
        _keyTuple,
        3,
        getValueSchema(),
        _index * 1,
        (_index + 1) * 1
      );
      return (bytes(_blob));
    }
  }

  /**
   * Get an item of baseCreations (using the specified store)
   * (unchecked, returns invalid data if index overflows)
   */
  function getItemBaseCreations(
    IStore _store,
    bytes32 creationId,
    uint256 _index
  ) internal view returns (bytes memory) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = creationId;

    unchecked {
      bytes memory _blob = _store.getFieldSlice(_tableId, _keyTuple, 3, getValueSchema(), _index * 1, (_index + 1) * 1);
      return (bytes(_blob));
    }
  }

  /** Push a slice to baseCreations */
  function pushBaseCreations(bytes32 creationId, bytes memory _slice) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = creationId;

    StoreSwitch.pushToField(_tableId, _keyTuple, 3, bytes((_slice)), getValueSchema());
  }

  /** Push a slice to baseCreations (using the specified store) */
  function pushBaseCreations(IStore _store, bytes32 creationId, bytes memory _slice) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = creationId;

    _store.pushToField(_tableId, _keyTuple, 3, bytes((_slice)), getValueSchema());
  }

  /** Pop a slice from baseCreations */
  function popBaseCreations(bytes32 creationId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = creationId;

    StoreSwitch.popFromField(_tableId, _keyTuple, 3, 1, getValueSchema());
  }

  /** Pop a slice from baseCreations (using the specified store) */
  function popBaseCreations(IStore _store, bytes32 creationId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = creationId;

    _store.popFromField(_tableId, _keyTuple, 3, 1, getValueSchema());
  }

  /**
   * Update a slice of baseCreations at `_index`
   * (checked only to prevent modifying other tables; can corrupt own data if index overflows)
   */
  function updateBaseCreations(bytes32 creationId, uint256 _index, bytes memory _slice) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = creationId;

    unchecked {
      StoreSwitch.updateInField(_tableId, _keyTuple, 3, _index * 1, bytes((_slice)), getValueSchema());
    }
  }

  /**
   * Update a slice of baseCreations (using the specified store) at `_index`
   * (checked only to prevent modifying other tables; can corrupt own data if index overflows)
   */
  function updateBaseCreations(IStore _store, bytes32 creationId, uint256 _index, bytes memory _slice) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = creationId;

    unchecked {
      _store.updateInField(_tableId, _keyTuple, 3, _index * 1, bytes((_slice)), getValueSchema());
    }
  }

  /** Get metadata */
  function getMetadata(bytes32 creationId) internal view returns (bytes memory metadata) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = creationId;

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 4, getValueSchema());
    return (bytes(_blob));
  }

  /** Get metadata (using the specified store) */
  function getMetadata(IStore _store, bytes32 creationId) internal view returns (bytes memory metadata) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = creationId;

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 4, getValueSchema());
    return (bytes(_blob));
  }

  /** Set metadata */
  function setMetadata(bytes32 creationId, bytes memory metadata) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = creationId;

    StoreSwitch.setField(_tableId, _keyTuple, 4, bytes((metadata)), getValueSchema());
  }

  /** Set metadata (using the specified store) */
  function setMetadata(IStore _store, bytes32 creationId, bytes memory metadata) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = creationId;

    _store.setField(_tableId, _keyTuple, 4, bytes((metadata)), getValueSchema());
  }

  /** Get the length of metadata */
  function lengthMetadata(bytes32 creationId) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = creationId;

    uint256 _byteLength = StoreSwitch.getFieldLength(_tableId, _keyTuple, 4, getValueSchema());
    unchecked {
      return _byteLength / 1;
    }
  }

  /** Get the length of metadata (using the specified store) */
  function lengthMetadata(IStore _store, bytes32 creationId) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = creationId;

    uint256 _byteLength = _store.getFieldLength(_tableId, _keyTuple, 4, getValueSchema());
    unchecked {
      return _byteLength / 1;
    }
  }

  /**
   * Get an item of metadata
   * (unchecked, returns invalid data if index overflows)
   */
  function getItemMetadata(bytes32 creationId, uint256 _index) internal view returns (bytes memory) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = creationId;

    unchecked {
      bytes memory _blob = StoreSwitch.getFieldSlice(
        _tableId,
        _keyTuple,
        4,
        getValueSchema(),
        _index * 1,
        (_index + 1) * 1
      );
      return (bytes(_blob));
    }
  }

  /**
   * Get an item of metadata (using the specified store)
   * (unchecked, returns invalid data if index overflows)
   */
  function getItemMetadata(IStore _store, bytes32 creationId, uint256 _index) internal view returns (bytes memory) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = creationId;

    unchecked {
      bytes memory _blob = _store.getFieldSlice(_tableId, _keyTuple, 4, getValueSchema(), _index * 1, (_index + 1) * 1);
      return (bytes(_blob));
    }
  }

  /** Push a slice to metadata */
  function pushMetadata(bytes32 creationId, bytes memory _slice) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = creationId;

    StoreSwitch.pushToField(_tableId, _keyTuple, 4, bytes((_slice)), getValueSchema());
  }

  /** Push a slice to metadata (using the specified store) */
  function pushMetadata(IStore _store, bytes32 creationId, bytes memory _slice) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = creationId;

    _store.pushToField(_tableId, _keyTuple, 4, bytes((_slice)), getValueSchema());
  }

  /** Pop a slice from metadata */
  function popMetadata(bytes32 creationId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = creationId;

    StoreSwitch.popFromField(_tableId, _keyTuple, 4, 1, getValueSchema());
  }

  /** Pop a slice from metadata (using the specified store) */
  function popMetadata(IStore _store, bytes32 creationId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = creationId;

    _store.popFromField(_tableId, _keyTuple, 4, 1, getValueSchema());
  }

  /**
   * Update a slice of metadata at `_index`
   * (checked only to prevent modifying other tables; can corrupt own data if index overflows)
   */
  function updateMetadata(bytes32 creationId, uint256 _index, bytes memory _slice) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = creationId;

    unchecked {
      StoreSwitch.updateInField(_tableId, _keyTuple, 4, _index * 1, bytes((_slice)), getValueSchema());
    }
  }

  /**
   * Update a slice of metadata (using the specified store) at `_index`
   * (checked only to prevent modifying other tables; can corrupt own data if index overflows)
   */
  function updateMetadata(IStore _store, bytes32 creationId, uint256 _index, bytes memory _slice) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = creationId;

    unchecked {
      _store.updateInField(_tableId, _keyTuple, 4, _index * 1, bytes((_slice)), getValueSchema());
    }
  }

  /** Get the full data */
  function get(bytes32 creationId) internal view returns (CreationRegistryData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = creationId;

    bytes memory _blob = StoreSwitch.getRecord(_tableId, _keyTuple, getValueSchema());
    return decode(_blob);
  }

  /** Get the full data (using the specified store) */
  function get(IStore _store, bytes32 creationId) internal view returns (CreationRegistryData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = creationId;

    bytes memory _blob = _store.getRecord(_tableId, _keyTuple, getValueSchema());
    return decode(_blob);
  }

  /** Set the full data using individual values */
  function set(
    bytes32 creationId,
    uint32 numVoxels,
    bytes memory voxelTypes,
    bytes memory relativePositions,
    bytes memory baseCreations,
    bytes memory metadata
  ) internal {
    bytes memory _data = encode(numVoxels, voxelTypes, relativePositions, baseCreations, metadata);

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = creationId;

    StoreSwitch.setRecord(_tableId, _keyTuple, _data, getValueSchema());
  }

  /** Set the full data using individual values (using the specified store) */
  function set(
    IStore _store,
    bytes32 creationId,
    uint32 numVoxels,
    bytes memory voxelTypes,
    bytes memory relativePositions,
    bytes memory baseCreations,
    bytes memory metadata
  ) internal {
    bytes memory _data = encode(numVoxels, voxelTypes, relativePositions, baseCreations, metadata);

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = creationId;

    _store.setRecord(_tableId, _keyTuple, _data, getValueSchema());
  }

  /** Set the full data using the data struct */
  function set(bytes32 creationId, CreationRegistryData memory _table) internal {
    set(
      creationId,
      _table.numVoxels,
      _table.voxelTypes,
      _table.relativePositions,
      _table.baseCreations,
      _table.metadata
    );
  }

  /** Set the full data using the data struct (using the specified store) */
  function set(IStore _store, bytes32 creationId, CreationRegistryData memory _table) internal {
    set(
      _store,
      creationId,
      _table.numVoxels,
      _table.voxelTypes,
      _table.relativePositions,
      _table.baseCreations,
      _table.metadata
    );
  }

  /**
   * Decode the tightly packed blob using this table's schema.
   * Undefined behaviour for invalid blobs.
   */
  function decode(bytes memory _blob) internal pure returns (CreationRegistryData memory _table) {
    // 4 is the total byte length of static data
    PackedCounter _encodedLengths = PackedCounter.wrap(Bytes.slice32(_blob, 4));

    _table.numVoxels = (uint32(Bytes.slice4(_blob, 0)));

    // Store trims the blob if dynamic fields are all empty
    if (_blob.length > 4) {
      // skip static data length + dynamic lengths word
      uint256 _start = 36;
      uint256 _end;
      unchecked {
        _end = 36 + _encodedLengths.atIndex(0);
      }
      _table.voxelTypes = (bytes(SliceLib.getSubslice(_blob, _start, _end).toBytes()));

      _start = _end;
      unchecked {
        _end += _encodedLengths.atIndex(1);
      }
      _table.relativePositions = (bytes(SliceLib.getSubslice(_blob, _start, _end).toBytes()));

      _start = _end;
      unchecked {
        _end += _encodedLengths.atIndex(2);
      }
      _table.baseCreations = (bytes(SliceLib.getSubslice(_blob, _start, _end).toBytes()));

      _start = _end;
      unchecked {
        _end += _encodedLengths.atIndex(3);
      }
      _table.metadata = (bytes(SliceLib.getSubslice(_blob, _start, _end).toBytes()));
    }
  }

  /** Tightly pack full data using this table's schema */
  function encode(
    uint32 numVoxels,
    bytes memory voxelTypes,
    bytes memory relativePositions,
    bytes memory baseCreations,
    bytes memory metadata
  ) internal pure returns (bytes memory) {
    PackedCounter _encodedLengths;
    // Lengths are effectively checked during copy by 2**40 bytes exceeding gas limits
    unchecked {
      _encodedLengths = PackedCounterLib.pack(
        bytes(voxelTypes).length,
        bytes(relativePositions).length,
        bytes(baseCreations).length,
        bytes(metadata).length
      );
    }

    return
      abi.encodePacked(
        numVoxels,
        _encodedLengths.unwrap(),
        bytes((voxelTypes)),
        bytes((relativePositions)),
        bytes((baseCreations)),
        bytes((metadata))
      );
  }

  /** Encode keys as a bytes32 array using this table's schema */
  function encodeKeyTuple(bytes32 creationId) internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = creationId;

    return _keyTuple;
  }

  /* Delete all data for given keys */
  function deleteRecord(bytes32 creationId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = creationId;

    StoreSwitch.deleteRecord(_tableId, _keyTuple, getValueSchema());
  }

  /* Delete all data for given keys (using the specified store) */
  function deleteRecord(IStore _store, bytes32 creationId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = creationId;

    _store.deleteRecord(_tableId, _keyTuple, getValueSchema());
  }
}
