// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { PositionData } from "@base-ca/src/codegen/Tables.sol";

interface IBaseCASystem {
  function enterWorld(bytes32 voxelTypeId, PositionData memory coord, bytes32 entity) external;
}
