// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { VoxelCoord } from "@tenet-utils/src/Types.sol";

interface ICAHelperSystem {
  function bodyEnterWorld(bytes32 bodyTypeId, VoxelCoord memory coord, bytes32 caEntity) external;

  function getBodyVariant(
    bytes32 bodyTypeId,
    bytes32 caEntity,
    bytes32[] memory caNeighbourEntityIds,
    bytes32[] memory childEntityIds,
    bytes32 parentEntity
  ) external returns (bytes32);

  function bodyExitWorld(bytes32 bodyTypeId, VoxelCoord memory coord, bytes32 caEntity) external;

  function bodyRunInteraction(
    bytes4 interactionSelector,
    bytes32 bodyTypeId,
    bytes32 caInteractEntity,
    bytes32[] memory caNeighbourEntityIds,
    bytes32[] memory childEntityIds,
    bytes32 parentEntity
  ) external returns (bytes32[] memory);
}
