// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { VoxelCoord } from "@tenet-utils/src/Types.sol";

interface ICallCASystem {
  function registerInitialVoxelType(
    bytes32 voxelTypeId,
    bytes4 enterWorldSelector,
    bytes4 exitWorldSelector,
    bytes4 voxelVariantSelector,
    bytes4 activateSelector,
    bytes4 interactionSelector
  ) external;

  function buildCAWorld(address callerAddress, bytes32 voxelTypeId, VoxelCoord memory coord) external;

  function mineCAWorld(address callerAddress, bytes32 voxelTypeId, VoxelCoord memory coord) external;
}
