// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface ICARegistrySystem {
  function registerCA(string memory name, string memory description, bytes32[] memory bodyTypeIds) external;

  function addBodyToCA(bytes32 bodyTypeId) external;
}
