// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IDecisionRuleRegSystem {
  function registerDecisionRule(
    string memory name,
    string memory description,
    bytes32 srcVoxelTypeId,
    bytes32 targetVoxelTypeId,
    string memory decisionRuleSelector
  ) external;

  function registerDecisionRuleForWorld(
    string memory name,
    string memory description,
    bytes32 srcVoxelTypeId,
    bytes32 targetVoxelTypeId,
    address worldAddress,
    string memory decisionRuleSelector
  ) external;
}
