// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IObjectRegistrySystem {
  function registerObjectType(
    bytes32 objectTypeId,
    address contractAddress,
    bytes4 enterWorldSelector,
    bytes4 exitWorldSelector,
    bytes4 eventHandlerSelector,
    bytes4 neighbourEventHandlerSelector,
    uint8 stackable,
    uint16 maxUses,
    string memory name
  ) external;
}
