// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { VoxelSelectors } from "@tenet-utils/src/Types.sol";
import { VoxelVariantsRegistryData } from "./../Tables.sol";

interface IVoxelRegistrySystem {
  function registerVoxelType(
    string memory voxelTypeName,
    bytes32 voxelTypeId,
    bytes32 baseVoxelTypeId,
    bytes32[] memory childVoxelTypeIds,
    bytes32[] memory schemaVoxelTypeIds,
    bytes32 previewVoxelVariantId,
    VoxelSelectors memory voxelSelectors
  ) external;

  function registerVoxelVariant(bytes32 voxelVariantId, VoxelVariantsRegistryData memory voxelVariant) external;

  function voxelSpawned(bytes32 voxelTypeId) external returns (uint256);
}
