create-instance:
	sh create-instance.sh
.PHONY: create-instance

deploy:
	sh deploy.sh
.PHONY: deploy

deploy-world:
	sh deploy-world.sh
.PHONY: deploy-world

deploy-extensions:
	sh deploy-extensions.sh
.PHONY: deploy-extensions