// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { VoxelCoord } from "@tenet-utils/src/Types.sol";

interface IRoadVoxelSystem {
  function registerVoxelRoad() external;

  function enterWorldRoad(address callerAddress, VoxelCoord memory coord, bytes32 entity) external;

  function exitWorldRoad(address callerAddress, VoxelCoord memory coord, bytes32 entity) external;

  function variantSelectorRoad(address callerAddress, bytes32 entity) external view returns (bytes32);
}
