// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

// Import schema type
import { SchemaType } from "@latticexyz/schema-type/src/solidity/SchemaType.sol";

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { Schema, SchemaLib } from "@latticexyz/store/src/Schema.sol";
import { PackedCounter, PackedCounterLib } from "@latticexyz/store/src/PackedCounter.sol";

bytes32 constant _tableId = bytes32(abi.encodePacked(bytes16(""), bytes16("Mind")));
bytes32 constant MindTableId = _tableId;

struct MindData {
  address mindAddress;
  bytes4 mindSelector;
}

library Mind {
  /** Get the table's key schema */
  function getKeySchema() internal pure returns (Schema) {
    SchemaType[] memory _schema = new SchemaType[](1);
    _schema[0] = SchemaType.BYTES32;

    return SchemaLib.encode(_schema);
  }

  /** Get the table's value schema */
  function getValueSchema() internal pure returns (Schema) {
    SchemaType[] memory _schema = new SchemaType[](2);
    _schema[0] = SchemaType.ADDRESS;
    _schema[1] = SchemaType.BYTES4;

    return SchemaLib.encode(_schema);
  }

  /** Get the table's key names */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](1);
    keyNames[0] = "objectEntityId";
  }

  /** Get the table's field names */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](2);
    fieldNames[0] = "mindAddress";
    fieldNames[1] = "mindSelector";
  }

  /** Register the table's key schema, value schema, key names and value names */
  function register() internal {
    StoreSwitch.registerTable(_tableId, getKeySchema(), getValueSchema(), getKeyNames(), getFieldNames());
  }

  /** Register the table's key schema, value schema, key names and value names (using the specified store) */
  function register(IStore _store) internal {
    _store.registerTable(_tableId, getKeySchema(), getValueSchema(), getKeyNames(), getFieldNames());
  }

  /** Get mindAddress */
  function getMindAddress(bytes32 objectEntityId) internal view returns (address mindAddress) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = objectEntityId;

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 0, getValueSchema());
    return (address(Bytes.slice20(_blob, 0)));
  }

  /** Get mindAddress (using the specified store) */
  function getMindAddress(IStore _store, bytes32 objectEntityId) internal view returns (address mindAddress) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = objectEntityId;

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 0, getValueSchema());
    return (address(Bytes.slice20(_blob, 0)));
  }

  /** Set mindAddress */
  function setMindAddress(bytes32 objectEntityId, address mindAddress) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = objectEntityId;

    StoreSwitch.setField(_tableId, _keyTuple, 0, abi.encodePacked((mindAddress)), getValueSchema());
  }

  /** Set mindAddress (using the specified store) */
  function setMindAddress(IStore _store, bytes32 objectEntityId, address mindAddress) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = objectEntityId;

    _store.setField(_tableId, _keyTuple, 0, abi.encodePacked((mindAddress)), getValueSchema());
  }

  /** Get mindSelector */
  function getMindSelector(bytes32 objectEntityId) internal view returns (bytes4 mindSelector) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = objectEntityId;

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 1, getValueSchema());
    return (Bytes.slice4(_blob, 0));
  }

  /** Get mindSelector (using the specified store) */
  function getMindSelector(IStore _store, bytes32 objectEntityId) internal view returns (bytes4 mindSelector) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = objectEntityId;

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 1, getValueSchema());
    return (Bytes.slice4(_blob, 0));
  }

  /** Set mindSelector */
  function setMindSelector(bytes32 objectEntityId, bytes4 mindSelector) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = objectEntityId;

    StoreSwitch.setField(_tableId, _keyTuple, 1, abi.encodePacked((mindSelector)), getValueSchema());
  }

  /** Set mindSelector (using the specified store) */
  function setMindSelector(IStore _store, bytes32 objectEntityId, bytes4 mindSelector) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = objectEntityId;

    _store.setField(_tableId, _keyTuple, 1, abi.encodePacked((mindSelector)), getValueSchema());
  }

  /** Get the full data */
  function get(bytes32 objectEntityId) internal view returns (MindData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = objectEntityId;

    bytes memory _blob = StoreSwitch.getRecord(_tableId, _keyTuple, getValueSchema());
    return decode(_blob);
  }

  /** Get the full data (using the specified store) */
  function get(IStore _store, bytes32 objectEntityId) internal view returns (MindData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = objectEntityId;

    bytes memory _blob = _store.getRecord(_tableId, _keyTuple, getValueSchema());
    return decode(_blob);
  }

  /** Set the full data using individual values */
  function set(bytes32 objectEntityId, address mindAddress, bytes4 mindSelector) internal {
    bytes memory _data = encode(mindAddress, mindSelector);

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = objectEntityId;

    StoreSwitch.setRecord(_tableId, _keyTuple, _data, getValueSchema());
  }

  /** Set the full data using individual values (using the specified store) */
  function set(IStore _store, bytes32 objectEntityId, address mindAddress, bytes4 mindSelector) internal {
    bytes memory _data = encode(mindAddress, mindSelector);

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = objectEntityId;

    _store.setRecord(_tableId, _keyTuple, _data, getValueSchema());
  }

  /** Set the full data using the data struct */
  function set(bytes32 objectEntityId, MindData memory _table) internal {
    set(objectEntityId, _table.mindAddress, _table.mindSelector);
  }

  /** Set the full data using the data struct (using the specified store) */
  function set(IStore _store, bytes32 objectEntityId, MindData memory _table) internal {
    set(_store, objectEntityId, _table.mindAddress, _table.mindSelector);
  }

  /** Decode the tightly packed blob using this table's schema */
  function decode(bytes memory _blob) internal pure returns (MindData memory _table) {
    _table.mindAddress = (address(Bytes.slice20(_blob, 0)));

    _table.mindSelector = (Bytes.slice4(_blob, 20));
  }

  /** Tightly pack full data using this table's schema */
  function encode(address mindAddress, bytes4 mindSelector) internal pure returns (bytes memory) {
    return abi.encodePacked(mindAddress, mindSelector);
  }

  /** Encode keys as a bytes32 array using this table's schema */
  function encodeKeyTuple(bytes32 objectEntityId) internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = objectEntityId;

    return _keyTuple;
  }

  /* Delete all data for given keys */
  function deleteRecord(bytes32 objectEntityId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = objectEntityId;

    StoreSwitch.deleteRecord(_tableId, _keyTuple, getValueSchema());
  }

  /* Delete all data for given keys (using the specified store) */
  function deleteRecord(IStore _store, bytes32 objectEntityId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = objectEntityId;

    _store.deleteRecord(_tableId, _keyTuple, getValueSchema());
  }
}
