// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { VoxelCoord } from "@tenet-utils/src/Types.sol";

interface IDirtVoxelSystem {
  function registerVoxelDirt() external;

  function enterWorldDirt(address callerAddress, VoxelCoord memory coord, bytes32 entity) external;

  function exitWorldDirt(address callerAddress, VoxelCoord memory coord, bytes32 entity) external;

  function variantSelectorDirt(address callerAddress, bytes32 entity) external view returns (bytes32);
}
