// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { VoxelCoord } from "@tenet-utils/src/Types.sol";

interface ISignalSourceVoxelSystem {
  function registerVoxelSignalSource() external;

  function enterWorldSignalSource(address callerAddress, VoxelCoord memory coord, bytes32 entity) external;

  function exitWorldSignalSource(address callerAddress, VoxelCoord memory coord, bytes32 entity) external;

  function variantSelectorSignalSource(address callerAddress, bytes32 entity) external view returns (bytes32);
}
