// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { VoxelCoord } from "@tenet-utils/src/Types.sol";

interface IWireVoxelSystem {
  function registerVoxelWire() external;

  function enterWorldWire(address callerAddress, VoxelCoord memory coord, bytes32 entity) external;

  function exitWorldWire(address callerAddress, VoxelCoord memory coord, bytes32 entity) external;

  function variantSelectorWire(address callerAddress, bytes32 entity) external view returns (bytes32);
}
