// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

// Import schema type
import { SchemaType } from "@latticexyz/schema-type/src/solidity/SchemaType.sol";

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { Schema, SchemaLib } from "@latticexyz/store/src/Schema.sol";
import { PackedCounter, PackedCounterLib } from "@latticexyz/store/src/PackedCounter.sol";

// Import user types
import { SimTable } from "@tenet-utils/src/Types.sol";

bytes32 constant _tableId = bytes32(abi.encodePacked(bytes16(""), bytes16("SimAction")));
bytes32 constant SimActionTableId = _tableId;

struct SimActionData {
  bytes4 transformationSelector;
  bytes4 transferSelector;
}

library SimAction {
  /** Get the table's key schema */
  function getKeySchema() internal pure returns (Schema) {
    SchemaType[] memory _schema = new SchemaType[](2);
    _schema[0] = SchemaType.UINT8;
    _schema[1] = SchemaType.UINT8;

    return SchemaLib.encode(_schema);
  }

  /** Get the table's value schema */
  function getValueSchema() internal pure returns (Schema) {
    SchemaType[] memory _schema = new SchemaType[](2);
    _schema[0] = SchemaType.BYTES4;
    _schema[1] = SchemaType.BYTES4;

    return SchemaLib.encode(_schema);
  }

  /** Get the table's key names */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](2);
    keyNames[0] = "senderTable";
    keyNames[1] = "receiverTable";
  }

  /** Get the table's field names */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](2);
    fieldNames[0] = "transformationSelector";
    fieldNames[1] = "transferSelector";
  }

  /** Register the table's key schema, value schema, key names and value names */
  function register() internal {
    StoreSwitch.registerTable(_tableId, getKeySchema(), getValueSchema(), getKeyNames(), getFieldNames());
  }

  /** Register the table's key schema, value schema, key names and value names (using the specified store) */
  function register(IStore _store) internal {
    _store.registerTable(_tableId, getKeySchema(), getValueSchema(), getKeyNames(), getFieldNames());
  }

  /** Get transformationSelector */
  function getTransformationSelector(
    SimTable senderTable,
    SimTable receiverTable
  ) internal view returns (bytes4 transformationSelector) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint8(senderTable)));
    _keyTuple[1] = bytes32(uint256(uint8(receiverTable)));

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 0, getValueSchema());
    return (Bytes.slice4(_blob, 0));
  }

  /** Get transformationSelector (using the specified store) */
  function getTransformationSelector(
    IStore _store,
    SimTable senderTable,
    SimTable receiverTable
  ) internal view returns (bytes4 transformationSelector) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint8(senderTable)));
    _keyTuple[1] = bytes32(uint256(uint8(receiverTable)));

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 0, getValueSchema());
    return (Bytes.slice4(_blob, 0));
  }

  /** Set transformationSelector */
  function setTransformationSelector(
    SimTable senderTable,
    SimTable receiverTable,
    bytes4 transformationSelector
  ) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint8(senderTable)));
    _keyTuple[1] = bytes32(uint256(uint8(receiverTable)));

    StoreSwitch.setField(_tableId, _keyTuple, 0, abi.encodePacked((transformationSelector)), getValueSchema());
  }

  /** Set transformationSelector (using the specified store) */
  function setTransformationSelector(
    IStore _store,
    SimTable senderTable,
    SimTable receiverTable,
    bytes4 transformationSelector
  ) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint8(senderTable)));
    _keyTuple[1] = bytes32(uint256(uint8(receiverTable)));

    _store.setField(_tableId, _keyTuple, 0, abi.encodePacked((transformationSelector)), getValueSchema());
  }

  /** Get transferSelector */
  function getTransferSelector(
    SimTable senderTable,
    SimTable receiverTable
  ) internal view returns (bytes4 transferSelector) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint8(senderTable)));
    _keyTuple[1] = bytes32(uint256(uint8(receiverTable)));

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 1, getValueSchema());
    return (Bytes.slice4(_blob, 0));
  }

  /** Get transferSelector (using the specified store) */
  function getTransferSelector(
    IStore _store,
    SimTable senderTable,
    SimTable receiverTable
  ) internal view returns (bytes4 transferSelector) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint8(senderTable)));
    _keyTuple[1] = bytes32(uint256(uint8(receiverTable)));

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 1, getValueSchema());
    return (Bytes.slice4(_blob, 0));
  }

  /** Set transferSelector */
  function setTransferSelector(SimTable senderTable, SimTable receiverTable, bytes4 transferSelector) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint8(senderTable)));
    _keyTuple[1] = bytes32(uint256(uint8(receiverTable)));

    StoreSwitch.setField(_tableId, _keyTuple, 1, abi.encodePacked((transferSelector)), getValueSchema());
  }

  /** Set transferSelector (using the specified store) */
  function setTransferSelector(
    IStore _store,
    SimTable senderTable,
    SimTable receiverTable,
    bytes4 transferSelector
  ) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint8(senderTable)));
    _keyTuple[1] = bytes32(uint256(uint8(receiverTable)));

    _store.setField(_tableId, _keyTuple, 1, abi.encodePacked((transferSelector)), getValueSchema());
  }

  /** Get the full data */
  function get(SimTable senderTable, SimTable receiverTable) internal view returns (SimActionData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint8(senderTable)));
    _keyTuple[1] = bytes32(uint256(uint8(receiverTable)));

    bytes memory _blob = StoreSwitch.getRecord(_tableId, _keyTuple, getValueSchema());
    return decode(_blob);
  }

  /** Get the full data (using the specified store) */
  function get(
    IStore _store,
    SimTable senderTable,
    SimTable receiverTable
  ) internal view returns (SimActionData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint8(senderTable)));
    _keyTuple[1] = bytes32(uint256(uint8(receiverTable)));

    bytes memory _blob = _store.getRecord(_tableId, _keyTuple, getValueSchema());
    return decode(_blob);
  }

  /** Set the full data using individual values */
  function set(
    SimTable senderTable,
    SimTable receiverTable,
    bytes4 transformationSelector,
    bytes4 transferSelector
  ) internal {
    bytes memory _data = encode(transformationSelector, transferSelector);

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint8(senderTable)));
    _keyTuple[1] = bytes32(uint256(uint8(receiverTable)));

    StoreSwitch.setRecord(_tableId, _keyTuple, _data, getValueSchema());
  }

  /** Set the full data using individual values (using the specified store) */
  function set(
    IStore _store,
    SimTable senderTable,
    SimTable receiverTable,
    bytes4 transformationSelector,
    bytes4 transferSelector
  ) internal {
    bytes memory _data = encode(transformationSelector, transferSelector);

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint8(senderTable)));
    _keyTuple[1] = bytes32(uint256(uint8(receiverTable)));

    _store.setRecord(_tableId, _keyTuple, _data, getValueSchema());
  }

  /** Set the full data using the data struct */
  function set(SimTable senderTable, SimTable receiverTable, SimActionData memory _table) internal {
    set(senderTable, receiverTable, _table.transformationSelector, _table.transferSelector);
  }

  /** Set the full data using the data struct (using the specified store) */
  function set(IStore _store, SimTable senderTable, SimTable receiverTable, SimActionData memory _table) internal {
    set(_store, senderTable, receiverTable, _table.transformationSelector, _table.transferSelector);
  }

  /** Decode the tightly packed blob using this table's schema */
  function decode(bytes memory _blob) internal pure returns (SimActionData memory _table) {
    _table.transformationSelector = (Bytes.slice4(_blob, 0));

    _table.transferSelector = (Bytes.slice4(_blob, 4));
  }

  /** Tightly pack full data using this table's schema */
  function encode(bytes4 transformationSelector, bytes4 transferSelector) internal pure returns (bytes memory) {
    return abi.encodePacked(transformationSelector, transferSelector);
  }

  /** Encode keys as a bytes32 array using this table's schema */
  function encodeKeyTuple(SimTable senderTable, SimTable receiverTable) internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint8(senderTable)));
    _keyTuple[1] = bytes32(uint256(uint8(receiverTable)));

    return _keyTuple;
  }

  /* Delete all data for given keys */
  function deleteRecord(SimTable senderTable, SimTable receiverTable) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint8(senderTable)));
    _keyTuple[1] = bytes32(uint256(uint8(receiverTable)));

    StoreSwitch.deleteRecord(_tableId, _keyTuple, getValueSchema());
  }

  /* Delete all data for given keys (using the specified store) */
  function deleteRecord(IStore _store, SimTable senderTable, SimTable receiverTable) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint8(senderTable)));
    _keyTuple[1] = bytes32(uint256(uint8(receiverTable)));

    _store.deleteRecord(_tableId, _keyTuple, getValueSchema());
  }
}
