// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { VoxelTypeRegistry, VoxelTypeRegistryData, VoxelTypeRegistryTableId } from "./tables/VoxelTypeRegistry.sol";
import { VoxelVariantsRegistry, VoxelVariantsRegistryData, VoxelVariantsRegistryTableId } from "./tables/VoxelVariantsRegistry.sol";
