// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { WorldRegistry, WorldRegistryData, WorldRegistryTableId } from "./tables/WorldRegistry.sol";
import { CARegistry, CARegistryData, CARegistryTableId } from "./tables/CARegistry.sol";
import { BodyTypeRegistry, BodyTypeRegistryData, BodyTypeRegistryTableId } from "./tables/BodyTypeRegistry.sol";
import { MindRegistry, MindRegistryTableId } from "./tables/MindRegistry.sol";
import { BodyVariantsRegistry, BodyVariantsRegistryData, BodyVariantsRegistryTableId } from "./tables/BodyVariantsRegistry.sol";
import { CreationRegistry, CreationRegistryData, CreationRegistryTableId } from "./tables/CreationRegistry.sol";
import { ClassifierRegistry, ClassifierRegistryData, ClassifierRegistryTableId } from "./tables/ClassifierRegistry.sol";
