/**
 * @fileoverview gRPC-Web generated client stub for Shard
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v4.23.3
// source: player.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.Shard = require('./player_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.Shard.PlayerServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.Shard.PlayerServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.Shard.Player,
 *   !proto.Shard.Player>}
 */
const methodDescriptor_PlayerService_UpdatePlayer = new grpc.web.MethodDescriptor(
  '/Shard.PlayerService/UpdatePlayer',
  grpc.web.MethodType.UNARY,
  proto.Shard.Player,
  proto.Shard.Player,
  /**
   * @param {!proto.Shard.Player} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.Shard.Player.deserializeBinary
);


/**
 * @param {!proto.Shard.Player} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.Shard.Player)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.Shard.Player>|undefined}
 *     The XHR Node Readable Stream
 */
proto.Shard.PlayerServiceClient.prototype.updatePlayer =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/Shard.PlayerService/UpdatePlayer',
      request,
      metadata || {},
      methodDescriptor_PlayerService_UpdatePlayer,
      callback);
};


/**
 * @param {!proto.Shard.Player} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.Shard.Player>}
 *     Promise that resolves to the response
 */
proto.Shard.PlayerServicePromiseClient.prototype.updatePlayer =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/Shard.PlayerService/UpdatePlayer',
      request,
      metadata || {},
      methodDescriptor_PlayerService_UpdatePlayer);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.Shard.Attack,
 *   !proto.Shard.Player>}
 */
const methodDescriptor_PlayerService_AttackPlayer = new grpc.web.MethodDescriptor(
  '/Shard.PlayerService/AttackPlayer',
  grpc.web.MethodType.UNARY,
  proto.Shard.Attack,
  proto.Shard.Player,
  /**
   * @param {!proto.Shard.Attack} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.Shard.Player.deserializeBinary
);


/**
 * @param {!proto.Shard.Attack} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.Shard.Player)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.Shard.Player>|undefined}
 *     The XHR Node Readable Stream
 */
proto.Shard.PlayerServiceClient.prototype.attackPlayer =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/Shard.PlayerService/AttackPlayer',
      request,
      metadata || {},
      methodDescriptor_PlayerService_AttackPlayer,
      callback);
};


/**
 * @param {!proto.Shard.Attack} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.Shard.Player>}
 *     Promise that resolves to the response
 */
proto.Shard.PlayerServicePromiseClient.prototype.attackPlayer =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/Shard.PlayerService/AttackPlayer',
      request,
      metadata || {},
      methodDescriptor_PlayerService_AttackPlayer);
};


module.exports = proto.Shard;

