setup:
	sh setup.sh
.PHONY: setup

run:
	sh run-node-and-client.sh
.PHONY: run

run-faucet:
	sh run-faucet.sh
.PHONY: run-faucet

run-snapshot:
	sh run-snapshotsh
.PHONY: run-snapshot

run-relay:
	sh run-relay.sh