// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { WorldConfig, WorldConfigTableId } from "./tables/WorldConfig.sol";
import { VoxelType, VoxelTypeData, VoxelTypeTableId } from "./tables/VoxelType.sol";
import { Position, PositionData, PositionTableId } from "./tables/Position.sol";
import { VoxelActivated, VoxelActivatedData, VoxelActivatedTableId } from "./tables/VoxelActivated.sol";
import { Interactions, InteractionsTableId } from "./tables/Interactions.sol";
import { OfSpawn, OfSpawnTableId } from "./tables/OfSpawn.sol";
import { Spawn, SpawnData, SpawnTableId } from "./tables/Spawn.sol";
