// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface ICraftSystem {
  function craft(bytes32 actingObjectEntityId, bytes32 recipeId, bytes32[] memory ingredientIds) external;
}
