// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IEquipSystem {
  function equip(bytes32 actingObjectEntityId, bytes32 inventoryId) external;
}
