// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IExternalCASystem {
  function getVoxelTypeId(uint32 scale, bytes32 entity) external view returns (bytes32);

  function calculateNeighbourEntities(uint32 scale, bytes32 centerEntity) external view returns (bytes32[] memory);

  function calculateChildEntities(uint32 scale, bytes32 entity) external view returns (bytes32[] memory);

  function calculateParentEntity(uint32 scale, bytes32 entity) external view returns (bytes32);
}
