// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { VoxelEntity } from "@tenet-utils/src/Types.sol";

interface IExternalCASystem {
  function getVoxelTypeId(VoxelEntity memory entity) external view returns (bytes32);

  function getMindSelector(VoxelEntity memory entity) external returns (bytes4);

  function shouldRunInteractionForNeighbour(
    VoxelEntity memory originEntity,
    VoxelEntity memory neighbourEntity
  ) external view returns (bool);

  function calculateNeighbourEntities(VoxelEntity memory centerEntity) external view returns (bytes32[] memory);

  function calculateChildEntities(VoxelEntity memory entity) external view returns (bytes32[] memory);

  function calculateParentEntity(VoxelEntity memory entity) external view returns (bytes32);
}
