// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { VoxelEntity } from "@tenet-utils/src/Types.sol";

interface IMindSystem {
  function setMindSelector(VoxelEntity memory entity, bytes4 mindSelector) external;
}
