// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IMindSystem {
  function setMindSelector(bytes32 objectEntityId, address mindAddress, bytes4 mindSelector) external;
}
