// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { VoxelCoord } from "@tenet-base-world/src/Types.sol";

interface IRunCASystem {
  function enterCA(
    address caAddress,
    uint32 scale,
    bytes32 voxelTypeId,
    bytes4 mindSelector,
    VoxelCoord memory coord,
    bytes32 entity
  ) external;

  function moveCA(
    address caAddress,
    uint32 scale,
    bytes32 voxelTypeId,
    VoxelCoord memory oldCoord,
    VoxelCoord memory newCoord,
    bytes32 newEntity
  ) external;

  function exitCA(
    address caAddress,
    uint32 scale,
    bytes32 voxelTypeId,
    VoxelCoord memory coord,
    bytes32 entity
  ) external;

  function activateCA(address caAddress, uint32 scale, bytes32 entity) external;

  function runCA(address caAddress, uint32 scale, bytes32 entity, bytes4 interactionSelector) external;
}
